{
  "uid" : "fe6529f654784281",
  "name" : "example1",
  "fullName" : "samples.SecondTestFile.example1",
  "historyId" : "45d4f7b64479d453b0ec350fc203ee82",
  "time" : {
    "start" : 1553092403416,
    "stop" : 1553092403422,
    "duration" : 6
  },
  "status" : "failed",
  "statusMessage" : "This test should be failed expected [3] but found [2]",
  "statusTrace" : "java.lang.AssertionError: This test should be failed expected [3] but found [2]\r\n\tat org.testng.Assert.fail(Assert.java:96)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:776)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:137)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:652)\r\n\tat samples.SecondTestFile.example1(SecondTestFile.java:10)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:40)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)\r\n\tat org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)\r\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "package",
    "value" : "samples.SecondTestFile"
  }, {
    "name" : "testClass",
    "value" : "samples.SecondTestFile"
  }, {
    "name" : "testMethod",
    "value" : "example1"
  }, {
    "name" : "parentSuite",
    "value" : "Suite1"
  }, {
    "name" : "suite",
    "value" : "test1"
  }, {
    "name" : "subSuite",
    "value" : "samples.SecondTestFile"
  }, {
    "name" : "host",
    "value" : "WS00CS001"
  }, {
    "name" : "thread",
    "value" : "75724@WS00CS001.TestNG-tests-1(13)"
  }, {
    "name" : "framework",
    "value" : "testng"
  }, {
    "name" : "language",
    "value" : "java"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "a703085ce3b1f42a",
      "status" : "failed",
      "statusDetails" : "This test should be failed expected [3] but found [2]",
      "time" : {
        "start" : 1553092235399,
        "stop" : 1553092235400,
        "duration" : 1
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "fe6529f654784281.json",
  "parameterValues" : [ ]
}